# Site settings
title: Students Materials
description: Materials for students of Belarusian State University (Faculty of Mathematics and Mechanics and Faculty of Applied Mathematics and Computer Science).
